#------------------------------------------------
# LaTeX makefile
#------------------------------------------------

all: hipodoc.tex
	pdflatex hipodoc.tex
clean:
	@rm -rf *.aux *.spl *synctex.gz hipodoc.pdf *.log
