//***********************************************************************
//***********************************************************************
//  HIPO 4.0
//=======================================================================
// Autogenerated code by HIPO 4.0 io library
// Modify the main loop to suite your needs
// Date: 07/17/2018
// Author: G.Gavalian
//***********************************************************************
#include <cstdlib>
#include <iostream>
#include "writer.h"

int main(int argc, char** argv) {

   std::cout << " writing file example program (HIPO) "  << __cplusplus << std::endl;

   char inputFile[256];

   if(argc>1) {
      sprintf(inputFile,"%s",argv[1]);
      //sprintf(outputFile,"%s",argv[2]);
   } else {
      std::cout << " *** please provide a file name..." << std::endl;
     exit(0);
   }

   char outputFile[256];
   sprintf(outputFile,"%s","exampleOutput.hipo");

   hipo::reader  reader;
   reader.open(inputFile);
   hipo::dictionary  factory;
   reader.readDictionary(factory);

   /*hipo::schema  sch("rec::event",30,1);
   sch.parse("pid/S,px/F,py/F,pz/F,vx/F,vy/F,vz/F");
   sch.show();*/

   hipo::writer  writer;
   writer.getDictionary().addSchema(factory.getSchema("REC::Traj"));
   writer.open(outputFile);


   hipo::bank traj(factory.getSchema("REC::Traj"));

   hipo::event      inEvent;
   hipo::event      outEvent;

   while(reader.next()==true){
      reader.read(inEvent);
      inEvent.getStructure(traj);
      outEvent.reset();
      if(traj.getRows()>0){
        outEvent.addStructure(traj);
        writer.addEvent(outEvent);
      }
    }

   writer.close();
   writer.showSummary();
}
//### END OF GENERATED CODE
